# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f702da285809ef34b42674b7386d50ff2826942101815e261ad338d8176590d77bdeb5174836e933e512432a3fd066ad53a4adee33ea1e0db461760cdb85203

test:
  secret_key_base: d8c8905538044d94840564e078f974bf6b689e25256ea8e60a95d2e7b915df88cf41b457c8be3328fded7ae63ef25ae10d320094dc52812ea5bd892213c9d5eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
